# convert from json to txt
---  
  
### [ formula ]  
x_tl, y_tl, w, h = bbox  
  
dw = 1.0 / img_width  
dh = 1.0 / img_height  
  
x_center = x_tl + w / 2.0  
y_center = y_tl + h / 2.0  
  
x = x_center * dw  
y = y_center * dh  
w = w * dw  
h = h * dh  
  
return [x, y, w, h]  
  
### [ before ]
- COCO bounding box format: **[top left x position, top left y position, width, height]**
- annotation(labeling)file type: **json**

### [ after ]
- YOLO bounding box format: **[x_center, y_center, width, height]**
- annotation(labeling)file type: **txt**

In [37]:
from pylabel import importer

In [46]:
path_to_annotations = "../data/downsample_data/Annotations/V2F_HY_9148_20201221_111302_E_CH0_Seoul_Sun_Mainroad_Day_97331_BBOX.json"
#path_to_images = "../data/downsample_data/Images/V2F_HY_9148_20201221_111302_E_CH0_Seoul_Sun_Mainroad_Day_97331.png"

In [47]:
#Import the dataset into the pylable schema 
dataset = importer.ImportCoco(path_to_annotations, path_to_images= path_to_images, name="BCCD_coco")
dataset.df.head(5)

,img_folder,img_filename,img_path,img_id,img_width,img_height,img_depth,ann_segmented,ann_bbox_xmin,ann_bbox_ymin,...,ann_segmentation,ann_iscrowd,ann_pose,ann_truncated,ann_difficult,cat_id,cat_name,cat_supercategory,split,annotated
id,,,,,,,,,,,,,,,,,,,,,
0,../data/downsample_data/Images/V2F_HY_9148_202...,V2F_HY_9148_20201221_111302_E_CH0_Seoul_Sun_Ma...,,1,1280,720,,,199.719809,43.373494,...,[],,,,,2,Person,,,1
1,../data/downsample_data/Images/V2F_HY_9148_202...,V2F_HY_9148_20201221_111302_E_CH0_Seoul_Sun_Ma...,,1,1280,720,,,318.852331,163.355684,...,[],,,,,4,Construction signs & Parking prohibited board,,,1

In [48]:
dataset.df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 0 to 1
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   img_folder         2 non-null      object
 1   img_filename       2 non-null      object
 2   img_path           2 non-null      object
 3   img_id             2 non-null      int64
 4   img_width          2 non-null      int32
 5   img_height         2 non-null      int32
 6   img_depth          2 non-null      object
 7   ann_segmented      2 non-null      object
 8   ann_bbox_xmin      2 non-null      float64
 9   ann_bbox_ymin      2 non-null      float64
 10  ann_bbox_xmax      2 non-null      float64
 11  ann_bbox_ymax      2 non-null      float64
 12  ann_bbox_width     2 non-null      float64
 13  ann_bbox_height    2 non-null      float64
 14  ann_area           2 non-null      float64
 15  ann_segmentation   2 non-null      object
 16  ann_iscrowd        2 non-null      object
 17  ann_pose           2 non-null      object
 18  ann_truncated      2 non-null      object
 19  ann_difficult      2 non-null      object
 20  cat_id             2 non-null      object
 21  cat_name           2 non-null      object
 22  cat_supercategory  2 non-null      object
 23  split              2 non-null      object
 24  annotated          2 non-null      int64
dtypes: float64(7), int32(2), int64(2), object(14)
memory usage: 400.0+ bytes

In [49]:
print(f"Number of images: {dataset.analyze.num_images}")
print(f"Number of classes: {dataset.analyze.num_classes}")
print(f"Classes:{dataset.analyze.classes}")
print(f"Class counts:\n{dataset.analyze.class_counts}")
print(f"Path to annotations:\n{dataset.path_to_annotations}")

Number of images: 1
Number of classes: 2
Classes:['Person', 'Construction signs & Parking prohibited board']
Class counts:
Person                                           1
Construction signs & Parking prohibited board    1
Name: cat_name, dtype: int64
Path to annotations:
..\data\downsample_data\Annotations

In [51]:
def convert_bbox_coco2yolo(img_width, img_height, bbox):
    """
    Convert bounding box from COCO  format to YOLO format

    Parameters
    ----------
    img_width : int
        width of image
    img_height : int
        height of image
    bbox : list[int]
        bounding box annotation in COCO format: 
        [top left x position, top left y position, width, height]

    Returns
    -------
    list[float]
        bounding box annotation in YOLO format: 
        [x_center_rel, y_center_rel, width_rel, height_rel]
    """
    
    # YOLO bounding box format: [x_center, y_center, width, height]
    # (float values relative to width and height of image)
    x_tl, y_tl, w, h = bbox

    dw = 1.0 / img_width
    dh = 1.0 / img_height

    x_center = x_tl + w / 2.0
    y_center = y_tl + h / 2.0

    x = x_center * dw
    y = y_center * dh
    w = w * dw
    h = h * dh

    return [x, y, w, h]

In [52]:
print(dataset.df.cat_id)
print(dataset.df.img_width)
print(dataset.df.img_height)
print(dataset.df.ann_bbox_xmin)
print(dataset.df.ann_bbox_ymin)
print(dataset.df.ann_bbox_xmax)
print(dataset.df.ann_bbox_ymax)
print(dataset.df.ann_bbox_width)
print(dataset.df.ann_bbox_height)

result = convert_bbox_coco2yolo(dataset.df.img_width, dataset.df.img_height, [dataset.df.ann_bbox_xmin, dataset.df.ann_bbox_ymin, dataset.df.ann_bbox_width, dataset.df.ann_bbox_height])

id
0    2
1    4
Name: cat_id, dtype: object
id
0    1280
1    1280
Name: img_width, dtype: int32
id
0    720
1    720
Name: img_height, dtype: int32
id
0    199.719809
1    318.852331
Name: ann_bbox_xmin, dtype: float64
id
0     43.373494
1    163.355684
Name: ann_bbox_ymin, dtype: float64
id
0    329.278932
1    375.549665
Name: ann_bbox_xmax, dtype: float64
id
0    305.631830
1    241.384687
Name: ann_bbox_ymax, dtype: float64
id
0    129.559122
1     56.697334
Name: ann_bbox_width, dtype: float64
id
0    262.258336
1     78.029004
Name: ann_bbox_height, dtype: float64

In [53]:
result

[id
 0    0.206640
 1    0.271251
 dtype: float64,
 id
 0    0.242365
 1    0.281070
 dtype: float64,
 id
 0    0.101218
 1    0.044295
 dtype: float64,
 id
 0    0.364248
 1    0.108374
 dtype: float64]